### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by ghost** [marcosschroh/youtube-audio-downloader#2]
Got it installed via pip but can't figure out how to make it work (on Windows)?

**Comment by marcosschroh** [comment]
I have never tried on Windows but it should work. 

Are you running it in a virtualenv?

**Comment by marcosschroh** [comment]
@mataxor Can you describe which errors are you having?

Thanks.

**Comment by marcosschroh** [comment]
@mataxor could you try to use this branch https://github.com/marcosschroh/youtube-audio-downloader/tree/windows-fixes ?

**Comment by marcosschroh** [comment]
@mataxor You can try on master branch now!
