### ISSUE TITLE
file type is .webm

### ISSUE THREAD

**Issue by imCalebM** [marcosschroh/youtube-audio-downloader#3]
I managed to download a song using your windows branch, but the file type is a webm

**Comment by marcosschroh** [comment]
Ok. So, means that has worked. Can you reproduce the .webm file? By default, it tries to get the best audio. I will add an extra option in which you can define the audio format.

**Comment by marcosschroh** [comment]
@imCalebM I've updated the code. Now you should use a conf file. You can specify the format that you want.
